README.md
pom.xml

To prevent projects from having to compile this project when they want to use it, an executable should be published.
In order to be able to publish an executable, such an executable must first be generated. This commit ensures that a stand-alone executable jar is generated during the maven 'package' phase.

Have project generate an executable jar

---

.github/workflows/build.yml
README.md
pom.xml

Upstream, Smack's integration-test module is now compiled with Java 11. Lets follow suit.

Increase minimum Java version from 8 to 11

---

pom.xml

4.12 has been reported to include a CVE. No functional changes are expected to be introduced in our project by this upgrade.

Upgrade junit dependency from 4.12 to 4.13.2

---

src/main/java/org/jivesoftware/smackx/pubsub/PubSubIntegrationTest.java

XEP-0060 defines optional functionality to delete items from a node. This commit adds a test for this, that's only executed when the corresponding feature is announced through service discovery.
As an aside, this tests the fix for Openfire's OF-2791 issue.

Add test to see if PubSub item can be deleted

---

pom.xml

Pull in latest changes from Smack (that includes Tagging and rework of existing tests.
This introduces a SNAPSHOT dependency, which should be replaced with a proper release (that's not available yet at the time that this commit was made).

Bump Smack dependency from 4.4.7 to 4.5.0-alpha4-SNAPSHOT

---

.github/workflows/build.yml
README.md
src/main/java/org/igniterealtime/smack/inttest/util/FileLogger.java
src/main/java/org/igniterealtime/smack/inttest/util/FileLoggerFactory.java

This adds a new Smack debug logger that can be used to store XMPP traffic in distinct files per test.
To configure the logger, use these system properties when invoking the tests:
```
-Dsinttest.debugger="org.igniterealtime.smack.inttest.util.FileLoggerFactory"
-DlogDir=target/logs
```
The `logDir` property value is used to identify the directory in which the logs will be stored. The directory will be created if it doesn't already exist.

Add ability to store XMPP logs in files

---

README.md
pom.xml
src/main/java/org/jivesoftware/smackx/pubsub/PubSubIntegrationTest.java

This includes a set of commits, one of which should be the v1.1 release.
In preparation of the release, the version of Smack is downgraded to a non-SNAPSHOT release. This allows us to have most new features of Smack, but still use a stable release.
I've also included a commit that applied the reference-tags to the existing tests in this repo (which _strictly speaking_ could have gone in another PR).

Release 1.1

---

src/main/java/org/igniterealtime/smack/inttest/util/JUnitXmlTestRunResultProcessor.java
src/test/java/org/igniterealtime/smack/inttest/util/JUnitXmlTestRunResultProcessorTest.java

The processor that generates JUnit-compatible XML reports attempts to generate an URL to the specifications that are under test.
Input used for these URLs should be properly escaped.
Links should be generated not only for XEP-specifications, but also for RFCs.
If a link can't be created, prevent the report generation from crashing. Instead, just generate a report without a link.
fixes #21

Improve JUnitXmlTestRunResultProcessor's URL generation

---

.github/workflows/build.yml
pom.xml

Recently, the Smack Integration Test Framework got a new configuration option, named 'host'. This allows the test to be configured with an IP address or DNS name of the XMPP service to run the tests on.
This new option negates the tricks involving setting `/etc/hosts` to make the XMPP domain name resolve to the intended host. This commit replaces that solution with the new configuration option.

Use SINT 'host' configuration option

---

src/main/java/org/jivesoftware/smackx/muc/MultiUserChatModeratorSubjectModIntegrationTest.java

Note that these tests will fail when using a version of Smack that does not fix a bug in its subject change implementation. See https://github.com/igniterealtime/Smack/pull/596

New tests for section "8.1 Moderator Use Cases: Modifying the Room Subject" of XEP-0045: "Multi-User Chat"

---

pom.xml
src/main/java/org/igniterealtime/smack/inttest/xep0363/HttpFileUploadExtIntegrationTest.java
src/main/java/org/igniterealtime/smack/inttest/xep0363/element/RetryError.java
src/main/java/org/igniterealtime/smack/inttest/xep0363/element/SlotRaw.java
src/main/java/org/igniterealtime/smack/inttest/xep0363/element/SlotRaw_V0_2.java
src/main/java/org/igniterealtime/smack/inttest/xep0363/package-info.java
src/main/java/org/igniterealtime/smack/inttest/xep0363/provider/RetryErrorProvider.java
src/main/java/org/igniterealtime/smack/inttest/xep0363/provider/SlotRawProvider.java

Note that in Openfire, unless the appropriate plugin is installed, these tests will be skipped.

Add tests for XEP-0363 HTTP File Upload

---

src/main/java/org/igniterealtime/smack/inttest/xep0215/ExternalServiceDiscoveryIntegrationTest.java
src/main/java/org/igniterealtime/smack/inttest/xep0215/package-info.java
src/main/java/org/igniterealtime/smack/inttest/xep0215/packet/DiscoverExternalServices.java
src/main/java/org/igniterealtime/smack/inttest/xep0215/packet/ServiceCredentials.java
src/main/java/org/igniterealtime/smack/inttest/xep0215/packet/package-info.java
src/main/java/org/igniterealtime/smack/inttest/xep0215/provider/DiscoverExternalServicesProvider.java
src/main/java/org/igniterealtime/smack/inttest/xep0215/provider/ServiceCredentialsProvider.java
src/main/java/org/igniterealtime/smack/inttest/xep0215/provider/package-info.java

Note that for Openfire, none of these tests can run (they'll be automatically skipped) unless the [External Service Discovery plugin](https://www.igniterealtime.org/projects/openfire/plugin-archive.jsp?plugin=externalservicediscovery) is loaded.
At the time of writing, that plugin contains on bug that is correctly identified by the tests that I'm adding in this PR. The ticket for that bug is here: https://github.com/igniterealtime/openfire-externalservicediscovery-plugin/issues/16

Add tests for XEP-0215 External Service Discovery

---

src/main/java/org/igniterealtime/smack/inttest/xep0054/VCardTempIntegrationTest.java
src/main/java/org/igniterealtime/smack/inttest/xep0054/package-info.java

Note that I expect Openfire to fail a couple of the tests introduced here, while these issues remain unresolved:
- https://igniterealtime.atlassian.net/browse/OF-2838
- https://igniterealtime.atlassian.net/browse/OF-2839
Both of them are addressed in https://github.com/igniterealtime/Openfire/pull/2470

Add tests for XEP-0054 vcard-temp

---

src/main/java/org/igniterealtime/smack/inttest/xep0115/EntityCapabilitiesIntegrationTest.java
src/main/java/org/igniterealtime/smack/inttest/xep0115/EntityCapabilitiesOptimizationIntegrationTest.java
src/main/java/org/igniterealtime/smack/inttest/xep0115/package-info.java
src/main/java/org/jivesoftware/smackx/caps/CapsUtil.java

Note that Openfire does not support the optional 'caps optimization' feature, for which tests are included. Those tests have thus not been tested.
A ticket to have support added to Openfire is raised in https://igniterealtime.atlassian.net/browse/OF-2837

Add tests for XEP-0115 Entity Capabilities

---

.github/workflows/build.yml

Java 21 is a LTS release. Let's use that in our CI too.

CI: Add Java 21 to list JDKs used for CI

---

src/main/java/org/igniterealtime/smack/inttest/xep0115/EntityCapabilitiesOptimizationIntegrationTest.java
src/main/java/org/igniterealtime/smack/inttest/xep0352/CsiIntegrationTest.java
src/main/java/org/jivesoftware/smackx/pubsub/PubSubExtIntegrationTest.java

This test is failing in Circle CI but not locally. I believe this to be a test ordering difference, and that a test that runs before this is subscribing conTwo to conOne, breaking the test.
I looked at tearing down the subscription in SubscriptionIntegrationTest, but this might not be where it's occuring, and this feels more explicit.

Enforce no presence subscription before testing presence pubsub model

---

src/main/java/org/igniterealtime/smack/inttest/xep0030/ServiceDiscoveryIntegrationTest.java

Even without a presence subscription, it is allowable for _some_ data to be advertised via disco#items.
Some of Smack's other tests publish PEP data (and do not clean that up, which is addressed in https://github.com/igniterealtime/Smack/pull/606) that would should up as disco#items. The test that is modified in this commit would erroneously fail on those.

Fix service discovery items test

---

.github/workflows/build.yml

In Openfire 4.8.2, improvements have been applied that make more of our tests go green.

CI: Use Openfire 4.8.2 instead of Openfire 4.8.1

---

.github/workflows/build.yml
src/main/java/org/igniterealtime/smack/inttest/util/FileLogger.java
src/main/java/org/igniterealtime/smack/inttest/util/JUnitXmlTestRunResultProcessor.java
src/main/java/org/igniterealtime/smack/inttest/util/StdOutTestRunResultProcessor.java

The output as printed on standard-out should facilitate viewers in debugging their code on test failures.
It needs to be as easy as possible to determine for each test failure:
- which specification was the subject of the test, containing a specification reference and a direct quote of the relevant text.
- what test assertion failed
- where the XMPP stanza log is for the test that fails.
Viewers need not be familiar with our test implementations (or even Smack, or Java). We can/should still reference the implementation as a last resort.
This is achieved by replacing SINT's standard Test Run Result processor (`org.igniterealtime.smack.inttest.SmackIntegrationTestFramework\$JulTestRunResultProcessor`) with a new, custom implementation: …

Improve test run output on standard-out

---

.github/workflows/build.yml
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatAdminBanIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatAdminBanListIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatAdminGrantMemberIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatAdminGrantModeratorIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatAdminMemberListIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatAdminModeratorListIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatAdminRevokeMemberIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatAdminRevokeModeratorIntegrationTest.java

I'm opening this PR as a draft (for your reviewing pleasure) as I've completed a boatload of tests for sections 9.1 through 9.5. On the to-do list are sections 9.6 to 9.9.
Some of these tests are expected to fail when executing against Openfire versions before 4.8.3 (because of https://igniterealtime.atlassian.net/browse/OF-2843 and https://igniterealtime.atlassian.net/browse/OF-2844).

Adds tests for XEP-0045 Multi-User Chat (section 9)

---

.github/workflows/build.yml

Add a build-and-test step for container builds as a test of the containerisation.
We expose some logs, but don't keep the container, nor do we publish test results - other jobs deal with the tests themselves.

Add docker testing to PR CI

---

src/main/java/org/jivesoftware/smackx/muc/MultiUserChatAdminMemberListIntegrationTest.java

This test asserts that items in a member list have required fields. To do so, the test retrieves a member list.
The user that is used to retreive the member list is a non-privileged user. The XEP does not mandate that such a user must be allowed to retrieve the memberlist. To prevent issues, a privileged user should be used instead. All other tests in this class do so - it appears that this test erroneously omits the grant of that privilege in the test fixture setup. This is corrected in this commit.

Fix privilege in MUC mucTestAdminMemberListItemCheck

---

src/main/java/org/igniterealtime/smack/inttest/xep0054/VCardTempIntegrationTest.java

When requesting a vCard from a non-existing user, an error must be returned. When requesting a vCard from a user that has no vCard, an error must also be returned.
There are two tests in our code that check the above.
There is a third definition (and we have test for that), that states that both errors must be the same.
When one of the first two tests fail, running the third test is not very useful. This commit skips that test in that case.

Fix VCard error equality check

---

src/main/java/org/jivesoftware/smackx/muc/MultiUserChatAdminBanIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatAdminBanListIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatAdminGrantMemberIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatAdminGrantModeratorIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatAdminMemberListIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatAdminModeratorListIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatAdminRevokeMemberIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatAdminRevokeModeratorIntegrationTest.java

Various tests did not explicitly use an admin user. Even when an owner technically should have all admin privileges, it is cleaner to explicitly execute the system under test with an admin user, when testing admin functionality.

Improve tests for XEP-0045 Multi-User Chat (section 9)

---

src/main/java/org/jivesoftware/smackx/pubsub/PubSubExtIntegrationTest.java

When setting up a test fixture, do not use optional functionality that may not be supported by the server.

Fixes pubsub test: do not use optional functionality

---

src/main/java/org/jivesoftware/smack/subscription/SubscriptionIntegrationTest.java

RFC 6120 section 3.1.1 reads:
>    When a user sends a presence subscription request to a potential
>    instant messaging and presence contact, the value of the 'to'
>    attribute MUST be a bare JID <contact@domainpart> rather than a full
>    JID <contact@domainpart/resourcepart>, since the desired result is
>    for the user to receive presence from all of the contact's resources,
>    not merely the particular resource specified in the 'to' attribute.
>    Use of bare JIDs also simplifies subscription processing, presence
>    probes, and presence notifications by the user's server and the
>    contact's server.
Some of our tests were erroneously using a full JID. That's fixed in this PR.

Fix subscription requests

---

src/main/java/org/jivesoftware/smackx/muc/MUCAvatarIntegrationTest.java

Sadly the XEP is not using very strict wording. These tests (of which 2 are duplicates) is all that's strictly defined, as far as I can tell.

Add integration tests for XEP-0486 "MUC Avatars"

---

.github/workflows/build.yml
pom.xml
src/main/java/org/jivesoftware/smackx/muc/MUCAvatarIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatAdminBanListIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatModeratorKickIntegrationTest.java

The new Smack beta has dropped some old API. This commit adjusts our code accordingly.
Sadly, one of the tests that ship with Smack now fail (see https://github.com/igniterealtime/Smack/pull/630 ). That test has been disabled in the CI for this project.

Update to Smack 4.5.0-beta2

---

.github/workflows/build.yml
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatOwnerAdminListIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatOwnerConfigRoomIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatOwnerCreateRoomIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatOwnerDestroyRoomIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatOwnerGrantAdminIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatOwnerGrantOwnerIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatOwnerIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatOwnerOwnerListIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatOwnerRevokeAdminIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatOwnerRevokeOwnerIntegrationTest.java

This contains all tests for section 10 "Owner Use Cases" of XEP-0045.
Some of the tests included here are completely or partially commented out, as they depend on fixes in the underlying library, Smack, such as:
- [SMACK-947](https://igniterealtime.atlassian.net/browse/SMACK-947) / https://github.com/igniterealtime/Smack/pull/614
- [SMACK-949](https://igniterealtime.atlassian.net/browse/SMACK-949)
- [SMACK-950](https://igniterealtime.atlassian.net/browse/SMACK-950) / https://github.com/igniterealtime/Smack/pull/616

Add tests for XEP-0045 Multi-User Chat (section 10)

---

.github/workflows/build.yml
pom.xml

beta3 includes a major change in Smack's build system, which also updates its minimum Java requirement from 8 to 11 (we were already using 11), and fixes the bug in the FormTest that was recently introduced.

Update to Smack 4.5.0-beta3

---

src/main/java/org/jivesoftware/smackx/muc/MultiUserChatAdminBanIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatAdminBanListIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatAdminGrantMemberIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatAdminGrantModeratorIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatAdminMemberListIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatAdminModeratorListIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatAdminRevokeMemberIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatAdminRevokeModeratorIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatInvitationIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatModeratorKickIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatModeratorSubjectModIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatOccupantPMIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatOwnerAdminListIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatOwnerConfigRoomIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatOwnerCreateRoomIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatOwnerDestroyRoomIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatOwnerGrantAdminIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatOwnerGrantOwnerIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatOwnerIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatOwnerOwnerListIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatOwnerRevokeAdminIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatOwnerRevokeOwnerIntegrationTest.java
src/main/java/org/jivesoftware/smackx/muc/MultiUserChatSecurityConsiderationsIntegrationTest.java

XEP-0045 version 1.35.1 was recently released by the XSF. This includes some improvements that we had suggested.
This commit updates the MUC tests to that version, which includes the bumping of the version identifier, modifications of modified texts, and the uncommenting of tests that we had already implemented in anticipation of this update.

Increase coverage of XEP-0045 to version 1.35.1

---

.github/workflows/downstream_releases.yml

Adds a job that triggers either manually or when a release is published.
Right now, this just makes a call to a waiting action in XMPP-Interop-Testing/xmpp-interop-tests-action (but sets up the parallelism for this to run against more).
Corresponding PR in the downstream repo: https://github.com/XMPP-Interop-Testing/xmpp-interop-tests-action/pull/21
I've intentionally created a fine-grained PAT that covers only this repo in the secret.
I decided that it was less cognitive load to have 
- 1 fine-grained token per downstream target repository
rather than 
- 1 fine-grained token for all GitHub things that required updating each time we add a new CI target
- 1 token for GitLab
- 1 more for each additional non-GitHub code host

Release Automation: Trigger Downstream Repos

---

.github/workflows/downstream_releases.yml

Fixes 2 problems.
**Problem 1:**
Use of the action gave the following error when calling the GitHub API:
```
{
"message": "Problems parsing JSON",
"documentation_url": "https://docs.github.com/rest/repos/repos#create-a-repository-dispatch-event",
"status": "400"
}
```
**Problem 2:**
Running the action gave a warning about use of `::set-output`
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files.

Fix downstream-triggering action

---

.github/workflows/downstream_releases.yml

When this repo has a release published, a PR will be opened on the Circle CI Orb repo.
Follows #71. I've added a GitHub PAT specific to the Orb repo to the config of this repo.
This branch was intended to do all of them, but:
* Woodpecker is still nascent
* Docker is homed here
* Bamboo isn't necessary - it takes a separate JAR
* GitLab is TODO - it's significantly harder, and would require careful use of curl requests to their API (but I've added a GitLab Pipeline Trigger token just in case)

Add triggering of automated update PRs for Circle CI orb

---

src/main/java/org/igniterealtime/smack/inttest/util/StdOutTestRunResultProcessor.java

The aggregation of reasons why tests were impossible to run used the same count for all reasons.
This commit fixes:
```
Results aggregated by specification:
• RFC6121: Extensible Messaging and Presence Protocol (XMPP): Instant Messaging ... 36 ✔  0 💀   7 ✖
✖ The following tests were impossible to run! ✖
• RFC6121: could not run 7 test(s) because: The test implementation requires the connection used for testing to not have sent initial presence (but current configuration causes initial presence to be sent automatically).
• RFC6121: could not run 7 test(s) because: Smack was unable to parse the data sent by the server: <item xmlns='jabber:iq:roster' jid='test-target-67ut7@example.org' subscription='foobar'/></query><error xmlns='jabber:client' code='500' …
```

Fix count of 'impossible' test aggregate

---

src/main/java/org/igniterealtime/smack/inttest/rfc6121/section8/RFC6121Section8_5_2_2_1_MessageIntegrationTest.java
src/main/java/org/igniterealtime/smack/inttest/util/AccountUtilities.java

Integration tests that verify that behavior defined in section 8.5.2.2.1 "Local User / localpart@domainpart / No Available or Connected Resources / Message" of section 8 "Server Rules for Processing XML Stanzas" of RFC6121.

Add tests for RFC 6121 Section 8.5.2.2.1 'Server Rules for Processing XML Stanzas'

---

src/main/java/org/igniterealtime/smack/inttest/rfc6121/section8/RFC6121Section8_5_2_1_3_IqIntegrationTest.java

Integration tests that verify that behavior defined in section 8.5.2.1.3 "Local User / localpart@domainpart / Available or Connected Resources / IQ" of section 8 "Server Rules for Processing XML Stanzas" of RFC6121.

Add tests for RFC 6121 Section 8.5.2.1.3 'Server Rules for Processing XML Stanzas'

---

src/main/java/org/igniterealtime/smack/inttest/rfc6121/RFC6121Section8dot5dot2dot1dot1StanzaProcessingLocalUserConnectedResourcesMessageIntegrationTest.java
src/main/java/org/igniterealtime/smack/inttest/rfc6121/section8/RFC6121Section8_5_2_1_1_MessageIntegrationTest.java

Integration tests that verify that behavior defined in section 8.5.2.1.1 "Local User / localpart@domainpart / Available or Connected Resources / Message" of section 8 "Server Rules for Processing XML Stanzas" of RFC6121.
This was a bit of a journey. Even though this is a subsection of a subsection of a subsection of a section of a chapter, this turned out to be some 60 different tests. 
Initially, most of the tests had a lengthy, slightly varying implementation. Even during initial development, that proved to be unmaintainable. I've refactored everything to use one, generic implementation that setup up the test, performs the execution of the system-under-test (sending a message stanza to a bare JID) and tear down. The assertions are passed to this method as an argument.
This setup makes …

Add tests for RFC 6121 Section 8.5.2.1.1 'Server Rules for Processing XML Stanzas'

---

src/main/java/org/igniterealtime/smack/inttest/rfc6121/section8/RFC6121Section8_5_3_2_1_MessageIntegrationTest.java

Integration tests that verify that behavior defined in section 8.5.3.2.1 "Local User / localpart@domainpart/resourcepart / No Resource Matches / Message" of section 8 "Server Rules for Processing XML Stanzas" of RFC6121.

Add tests for RFC 6121 Section 8.5.3.2.1 'Server Rules for Processing XML Stanzas'

---

src/main/java/org/igniterealtime/smack/inttest/rfc6121/section8/RFC6121Section8_5_2_1_2_PresenceIntegrationTest.java
src/main/java/org/igniterealtime/smack/inttest/util/MarkerExtension.java

Integration tests that verify that behavior defined in section 8.5.2.1.2 "Local User / localpart@domainpart / Available or Connected Resources / Presence" of section 8 "Server Rules for Processing XML Stanzas" of RFC6121.
The tests here only partially cover this paragraph, as the paragraph references other paragraphs for most of its definition. The implementation added in this commit tests the processing of presence stanzas with no type or of type 'unavailable' only. All other types are/should be subject of tests under other sections (Section 3 and Section 4.3), to which section 8.5.2.1.2 references (and which have a much more detailed definition of the desired functionality).

Add tests for RFC 6121 Section 8.5.2.1.2 'Server Rules for Processing XML Stanzas'

---

src/main/java/org/igniterealtime/smack/inttest/rfc6121/section8/RFC6121Section8_5_1_IntegrationTest.java

This adds tests for the specification in RFC 6121, chapter 8 'Server Rules for Processing XML Stanzas', section 8.5 'Local User', paragraph 8.5.1 'No Such User'

Add tests for RFC 6121 Section 8.5.1 'No Such User'

---

src/main/java/org/igniterealtime/smack/inttest/rfc6121/section8/RFC6121Section8_5_3_1_IntegrationTest.java

Integration tests that verify that behavior defined in section 8.5.3.1 "Local User / localpart@domainpart/resourcepart / Resource Matches" of section 8 "Server Rules for Processing XML Stanzas" of RFC6121.

Add tests for RFC 6121 Section 8.5.3.1 'Server Rules for Processing XML Stanzas'

---

src/main/java/org/igniterealtime/smack/inttest/rfc6121/section8/RFC6121Section8_5_3_2_3_IqIntegrationTest.java

The RosterIntegrationTest frequently fails. Through debugging, we've established that this happens when the Roster's IQRequestHandler that processes roster pushes is not invoked (even though a corresponding stanza is received).
The source for this problem has been tracked down to RFC6121Section8_5_3_2_3_IqIntegrationTest. This test replaces IQRequestHandlers with an instance that's used by the test. The intention is to restore the handler that was replaced after the test has finished execution.
This commit fixes a bug that prevented the restoration of the original IQRequestHandler.
In the test, the handlers for multiple connections are replaced. The old values, however, are not stored _per connection_. This causes some connections to not get their original handler restored.

Fix #110: Inconsistent results for RosterIntegrationTest

---

src/main/java/org/igniterealtime/smack/inttest/rfc6121/section8/RFC6121Section8_5_2_2_1_MessageIntegrationTest.java
src/main/java/org/igniterealtime/smack/inttest/rfc6121/section8/RFC6121Section8_5_2_2_3_IqIntegrationTest.java
src/main/java/org/igniterealtime/smack/inttest/rfc6121/section8/RFC6121Section8_5_3_1_IntegrationTest.java
src/main/java/org/igniterealtime/smack/inttest/xep0198/StreamManagementLowLevelIntegrationTest.java

Some tests (and teardown methods) catch exceptions thrown, wrap that in a RuntimeException, and rethrow that.
This is likely the result of some kind of default IDE-based code template.
Rethrowing as a RuntimeException is undesirable. It doesn't notably change the semantic of the failure. It can cause the execution of all following tests to be aborted (as SmackIntegrationTestFramework isn't expecting instances of RuntimeException).
This commit throws the exception that was previously wrapped.
fixes #99

Don't wrap test exceptions in RuntimeException

---

src/main/java/org/igniterealtime/smack/inttest/rfc6121/section8/RFC6121Section8_5_1_IntegrationTest.java

For tests that can be expected to change a roster, make sure that such change is undone when tearing down the test fixture.
This helps to prevent tests from affecting each-other
fixes #102

Cleanup Roster-based test fixtures

---

src/main/java/org/igniterealtime/smack/inttest/xep0133/AbstractAdHocCommandIntegrationTest.java
src/main/java/org/igniterealtime/smack/inttest/xep0133/AdHocCommandIntegrationTest.java

If the runner is configured to use three explicitly named accounts (instead of an admin account that creates accounts as desired), the tests for ad-hoc commands crash. These tests require an administrative account.
In this comment, these tests raise a TestNotPossibleException, rather than cause a crash. This allows other tests to continue.

Skip ad-hoc tests when not provisioned with an admin account

---

.github/workflows/build.yml

Prior to this PR, the workflows of this repository test the built java version, as well as one of the containers, against a running XMPP server.
In this PR, that test is expanded with new tests, that each use different test account provisioning options (#126)
As an aside, this PR also contains the following change: Replace boilerplate code with GitHub Action
The continuous integration workflow starts an Openfire server for testing. In this commit, all of the related instructions are replaced with the GitHub action that is provided in https://github.com/igniterealtime/launch-openfire-action which does the same thing.

CI: add tests for each account provisioning method

---

.dockerignore
.github/workflows/entrypoint-test.yml
entrypoint.sh
test/entrypoint.bats

Adds:
- Entrypoint check for providing 0 or 3 test accounts, nothing in between
- Entrypoint check for providing test accounts or an admin account, not both
- BATS tests for the entrypoint script, given that we've accumulated logic for it
- GitHub Action to run the BATS tests
Fixes #128

Add entrypoint check for exactly 0 or 3 test accounts

---

.github/workflows/downstream_releases.yml

This is largely a copy-paste of other the GitHub jobs above it
This matches the other part in https://github.com/XMPP-Interop-Testing/xmpp-interop-tests-jenkins/pull/7
Introduces a new TOKEN_FOR_JENKINS_REPO secret, another PAT, configured identically to the one in #71

Add downstream trigger for Jenkins repo

---

.github/workflows/downstream_releases.yml

Matching part to https://github.com/XMPP-Interop-Testing/xmpp-interop-tests-drone-plugin/pull/13
Introduces a new TOKEN_FOR_DRONE_REPO secret, another PAT, configured identically to the one in https://github.com/XMPP-Interop-Testing/smack-sint-server-extensions/pull/71

Add downstream trigger for Drone repo
